[program:emya]
command=pnpm run start
directory=/data/emya
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
stopsignal=QUIT
user=root
redirect_stderr=true
stdout_logfile=/data/emya/logs/supervisord.log
